### ISSUE TITLE
Warnings "...has no existing object, this might lead to an error in future versions" since JS Controller 3.3 update

### ISSUE THREAD

**Issue by Pittini** [MeisterTR/ioBroker.yeelight#124]
I got those warnings at Adapter start and single warnings when updating one of those Datapoints. I've already deleted the complete tree, the Adapter have recreated them, but the warnings still exist.

<html>
<body>

yeelight-2.0 | 2021-09-28 22:11:02.978 | warn | State "yeelight-2.0.Strip1.control.sat" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
yeelight-2.0 | 2021-09-28 22:11:02.978 | warn | State "yeelight-2.0.Strip1.control.hue" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2021-09-28 22:11:02.977 | warn | State "yeelight-2.0.Strip1.control.color_mode" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2021-09-28 22:11:02.976 | warn | State "yeelight-2.0.Strip1.control.rgb" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2021-09-28 22:11:02.974 | warn | State "yeelight-2.0.Strip1.control.ct" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2021-09-28 22:11:02.968 | warn | State "yeelight-2.0.Strip1.control.active_bright" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2021-09-28 22:11:02.967 | warn | State "yeelight-2.0.Strip1.control.power" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2021-09-28 22:11:02.967 | warn | State "yeelight-2.0.Strip1.control.set_scene" has no existing object, this might lead to an error in future versions

</body>
</html>

**Comment by haselchen** [comment]
@Pittini 
Dem schliesse ich mich an. 
Habe exakt die gleichen Meldungen.
Ist der Entwickler noch aktiv?


@MeisterTR

**Comment by Lumumba76** [comment]
Same for me :-(

**Comment by ArchGithub** [comment]
Ich habe das gleiche Problem.

**Comment by Lumumba76** [comment]
Der Entwickler scheint nicht mehr aktiv zu sein....

**Comment by haselchen** [comment]
Problem mit einer Pendelleuchte und JS-Controller 4.0.21

`<html><body>


yeelight-2.0 | 2022-03-19 15:55:00.904 | info | (4399)  State value to set for  "yeelight-2.0.ceiling10-0x0000000007653fe3.control.bg_ct" has to be type  "number" but received type "string"
-- | -- | -- | --
yeelight-2.0 | 2022-03-19 15:55:00.897 | info | (4399)  State value to set for  "yeelight-2.0.ceiling10-0x0000000007653fe3.control.bg_sat" has to be  type "number" but received type "string"
yeelight-2.0 | 2022-03-19 15:55:00.895 | info | (4399)  State value to set for  "yeelight-2.0.ceiling10-0x0000000007653fe3.control.bg_hue" has to be  type "number" but received type "string"
yeelight-2.0 | 2022-03-19 15:55:00.893 | info | (4399)  State value to set for  "yeelight-2.0.ceiling10-0x0000000007653fe3.control.bg_bright" has to be  type "number" but received type "string"


</body>
</html>`

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by Pittini** [comment]
> Please try GitHub version

Newest version from beta repo:

<html>
<body>


yeelight-2.0 | 2022-05-21 13:41:17.235 | warn | State "yeelight-2.0.Strip1.info.Port" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
yeelight-2.0 | 2022-05-21 13:41:17.234 | warn | State "yeelight-2.0.Strip1.info.IPAdress" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2022-05-21 13:41:17.214 | warn | State "yeelight-2.0.Strip1.info.com" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2022-05-21 13:41:17.214 | warn | State "yeelight-2.0.White2.info.Port" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2022-05-21 13:41:17.213 | warn | State "yeelight-2.0.White2.info.IPAdress" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2022-05-21 13:41:17.213 | warn | State "yeelight-2.0.White2.info.com" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2022-05-21 13:41:17.212 | warn | State "yeelight-2.0.White1.info.Port" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2022-05-21 13:41:17.212 | warn | State "yeelight-2.0.White1.info.IPAdress" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2022-05-21 13:41:17.211 | warn | State "yeelight-2.0.White1.info.com" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2022-05-21 13:41:17.210 | warn | State "yeelight-2.0.color-0x0000000007e3cadb.info.Port" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2022-05-21 13:41:17.210 | warn | State "yeelight-2.0.color-0x0000000007e3cadb.info.IPAdress" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2022-05-21 13:41:17.209 | warn | State "yeelight-2.0.color-0x0000000007e3cadb.info.com" has no existing object, this might lead to an error in future versions
yeelight-2.0 | 2022-05-21 13:41:17.086 | info | starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v12.18.4, js-controller: 4.0.23
host.Iobroker | 2022-05-21 13:41:15.500 | info | instance system.adapter.yeelight-2.0 started with pid 8496
host.Iobroker | 2022-05-21 13:41:12.970 | info | instance system.adapter.yeelight-2.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)


</body>
</html>

**Comment by Apollon77** [comment]
Fixed on GitHub

**Comment by Pittini** [comment]
> Fixed on GitHub

Checked and acknowledged.
