### ISSUE TITLE
Yeelight Screen Bar Pro not Supportet?!

### ISSUE THREAD

**Issue by Manu4771** [MeisterTR/ioBroker.yeelight#157]
Hello, it´s my first time in GitHub, cause i´m mor elike the casual user. So exevuse me if this does not fit here... 

I have a Yeelight Screen Bar Pro with Whit elight for the Desk and RGB lights on the back for some ambientlight. 
It also supports Razer Chroma nd Overwolf. 

To finish my setup I realy want to use this Yeelight with this Adapter in ioBroker. But I think this light is not supportet at the moment right? I tested it several times: 
I get an connection but i´m not able to control the lighbar. 

If there is an developer who wants to do me the pleasure with making the adapter suppert the screen light I would be realy Thankfull.

I´can test anything you want. :) 

Thanks in advance.

**Comment by Typ1er** [comment]
I have the normal screenbar without pro. The main lamp always works for me, the RGBs seems to hang up, rarely works. In one of 100 attempts it works once.


I have set "color". I would like to know why it hangs.
