### ISSUE TITLE
Error with BedsideLamp2

### ISSUE THREAD

**Issue by MaTr75** [MeisterTR/ioBroker.yeelight#164]
I have a problem with my BedsideLamp2. When trying to switch der Object "power" I get the following error-message in the log-file:

Could not set state (power) to value (false) for device: 0x000000000000000. Error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

When I switch the lamp manually or by using the yeelight app the datapoints in the IOBroker are being updated correctly. So, the network connection should be working correctly.

Any idea, what might go wrong or where I can search for the error?

**Comment by Apollon77** [comment]
It seems thatthe local connection to the lamp is not established when you try to control it. Please provide a debug log
