### ISSUE TITLE
info.connect not captured correctly

### ISSUE THREAD

**Issue by FogfiRED** [MeisterTR/ioBroker.yeelight#175]
Hi there,

I'm using the github-version with my Yeelight 650 i'd like to use the object info.connect

If the light is switched on (wall-switch) the value is "true" all the time, so far so good.
If the light is switched off (no power wall-switch) the value changes from "true" to "false" and vice versa randomly. It should be "false".

**Comment by Apollon77** [comment]
Please provide a debug lebvel log of the adapter. Change loglebel for instance using Admin in exportmode

**Comment by FogfiRED** [comment]
Please see the log file below. Until 21:10:07 the wall-switch was off and my Yeelight had no Power. Hoever the object info.connect status changed to "true" at 21:05:45, back to "false" at 21:07:42, back to "true" at  21:08:42, back to "false" at 21:09:42.
At 21:10:42 it changed to "false" even though the wall-switch was switched on at this time (arround 21:10:00). Since 21:12:36 it stays "true" with wall-switch on.

<table><tbody><tr class="debug"><td>2022-05-30 21:03:42.556  - <span class="type">debug</span>: yeelight-2.0 (3148) DEVICES IN CONFIG: [{"name":"ceiling4-0x0000000005e880b4","ip":"192.168.123.45","port":"55443","smart_name":"","type":"ceiling4","id":"0x0000000005e880b4"}]</td></tr><tr class="debug"><td>2022-05-30 21:03:42.599  - <span class="type">debug</span>: yeelight-2.0 (3148) DEVICES IN OBJECTS: {"yeelight-2.0.ceiling4-0x0000000005e880b4":{"type":"device","common":{"name":"ceiling4","icon":"/icons/ceiling4.png"},"native":{"sid":"ceiling4-0x0000000005e880b4","type":"ceiling4"},"from":"system.adapter.yeelight-2.0","user":"system.user.admin","ts":1648373280347,"_id":"yeelight-2.0.ceiling4-0x0000000005e880b4","acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"},"enums":{}}}</td></tr><tr class="debug"><td>2022-05-30 21:03:42.600  - <span class="type">debug</span>: yeelight-2.0 (3148) DEVICES IN OBJECTS FOUND: 1</td></tr><tr class="debug"><td>2022-05-30 21:03:42.600  - <span class="type">debug</span>: yeelight-2.0 (3148) OBJ_ELEMENT: yeelight-2.0.ceiling4-0x0000000005e880b4</td></tr><tr class="debug"><td>2022-05-30 21:03:42.606  - <span class="type">debug</span>: yeelight-2.0 (3148) OLD CONF. FROM OBJ: {"name":"ceiling4-0x0000000005e880b4","ip":"192.168.123.45","port":"55443","smart_name":"","type":"ceiling4","id":"0x0000000005e880b4"}</td></tr><tr class="debug"><td>2022-05-30 21:03:42.607  - <span class="type">debug</span>: yeelight-2.0 (3148) SMARTNAME: </td></tr><tr class="debug"><td>2022-05-30 21:03:42.617  - <span class="type">debug</span>: yeelight-2.0 (3148) YEELIGHT FOUND: 192.168.123.45:55443  id: 0x0000000005e880b4 model: ceiling4</td></tr><tr class="debug"><td>2022-05-30 21:03:45.631  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:04:08.638  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:04:18.640  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:04:31.644  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:04:38.641  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:33846)</td></tr><tr class="debug"><td>2022-05-30 21:04:42.614  - <span class="type">debug</span>: yeelight-2.0 (3148) YEELIGHT OFFLINE: 0x0000000005e880b4</td></tr><tr class="debug"><td>2022-05-30 21:04:51.644  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:33850)</td></tr><tr class="debug"><td>2022-05-30 21:05:04.652  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:05:11.648  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:05:24.652  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:05:27.658  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:05:34.653  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:33864)</td></tr><tr class="info"><td>2022-05-30 21:05:35.233  - <span class="type">info</span>: history.0 (476) enabled logging of yeelight-2.0.ceiling4-0x0000000005e880b4.info.connect, Alias=false</td></tr><tr class="debug"><td>2022-05-30 21:05:44.652  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:33892)</td></tr><tr class="debug"><td>2022-05-30 21:05:50.664  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:05:57.659  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:33912)</td></tr><tr class="debug"><td>2022-05-30 21:06:07.660  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:06:10.665  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:06:17.660  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:06:23.672  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:06:27.661  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:33924)</td></tr><tr class="debug"><td>2022-05-30 21:06:33.672  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:06:37.661  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:33928)</td></tr><tr class="debug"><td>2022-05-30 21:06:43.672  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:06:46.678  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:06:49.684  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:06:53.674  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:33956)</td></tr><tr class="debug"><td>2022-05-30 21:07:00.668  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:07:03.673  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:33982)</td></tr><tr class="debug"><td>2022-05-30 21:07:07.664  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:33984)</td></tr><tr class="debug"><td>2022-05-30 21:07:12.690  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:07:15.696  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:07:18.702  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:07:20.670  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:33992)</td></tr><tr class="debug"><td>2022-05-30 21:07:26.684  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:07:32.691  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:33996)</td></tr><tr class="debug"><td>2022-05-30 21:07:35.697  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34000)</td></tr><tr class="debug"><td>2022-05-30 21:07:38.702  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34002)</td></tr><tr class="debug"><td>2022-05-30 21:07:42.613  - <span class="type">debug</span>: yeelight-2.0 (3148) YEELIGHT OFFLINE: 0x0000000005e880b4</td></tr><tr class="debug"><td>2022-05-30 21:07:45.696  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:07:46.685  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34006)</td></tr><tr class="debug"><td>2022-05-30 21:07:50.672  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34008)</td></tr><tr class="debug"><td>2022-05-30 21:07:59.692  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:08:02.697  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:08:05.698  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34034)</td></tr><tr class="debug"><td>2022-05-30 21:08:11.710  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:08:16.687  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34060)</td></tr><tr class="debug"><td>2022-05-30 21:08:20.673  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34062)</td></tr><tr class="debug"><td>2022-05-30 21:08:22.699  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:08:31.711  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34066)</td></tr><tr class="debug"><td>2022-05-30 21:08:35.701  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34068)</td></tr><tr class="debug"><td>2022-05-30 21:08:42.700  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34070)</td></tr><tr class="debug"><td>2022-05-30 21:08:48.694  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:08:51.702  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:08:54.708  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:04.720  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:07.726  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:10.732  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:12.702  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34088)</td></tr><tr class="debug"><td>2022-05-30 21:09:17.716  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:20.722  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:23.728  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:24.720  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34138)</td></tr><tr class="debug"><td>2022-05-30 21:09:30.732  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:33.738  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:36.744  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:37.727  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34146)</td></tr><tr class="debug"><td>2022-05-30 21:09:40.733  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34148)</td></tr><tr class="debug"><td>2022-05-30 21:09:42.612  - <span class="type">debug</span>: yeelight-2.0 (3148) YEELIGHT OFFLINE: 0x0000000005e880b4</td></tr><tr class="debug"><td>2022-05-30 21:09:43.728  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:46.734  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:49.740  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:50.732  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34158)</td></tr><tr class="debug"><td>2022-05-30 21:09:53.738  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34160)</td></tr><tr class="debug"><td>2022-05-30 21:09:56.736  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:09:59.742  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:10:02.748  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EHOSTUNREACH 192.168.123.45:55443</td></tr><tr class="debug"><td>2022-05-30 21:10:03.739  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34168)</td></tr><tr class="debug"><td>2022-05-30 21:10:06.745  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34170)</td></tr><tr class="debug"><td>2022-05-30 21:10:07.749  - <span class="type">debug</span>: yeelight-2.0 (3148) RESPONSE MESSAGE: from: 0x0000000005e880b4, id: 1, result:[on,61,,2,3800,61,0,,,0,on,on,,100,197,94,830697,6500]}</td></tr><tr class="debug"><td>2022-05-30 21:10:07.749  - <span class="type">debug</span>: yeelight-2.0 (3148) INITINAL ID FOUND FOR: ceiling4-0x0000000005e880b4</td></tr><tr class="debug"><td>2022-05-30 21:10:07.750  - <span class="type">debug</span>: yeelight-2.0 (3148) DEVICE FOUND IN AND CONFIG: {"name":"ceiling4-0x0000000005e880b4","ip":"192.168.123.45","port":"55443","smart_name":"","type":"ceiling4","id":"0x0000000005e880b4"}</td></tr><tr class="debug"><td>2022-05-30 21:10:10.735  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EISCONN 192.168.123.45:55443 - Local (192.168.178.30:34172)</td></tr><tr class="debug"><td>2022-05-30 21:10:16.736  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34174)</td></tr><tr class="debug"><td>2022-05-30 21:10:19.742  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EALREADY 192.168.123.45:55443 - Local (192.168.178.30:34176)</td></tr><tr class="debug"><td>2022-05-30 21:10:23.742  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EISCONN 192.168.123.45:55443 - Local (192.168.178.30:34178)</td></tr><tr class="debug"><td>2022-05-30 21:10:32.750  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EISCONN 192.168.123.45:55443 - Local (192.168.178.30:34202)</td></tr><tr class="debug"><td>2022-05-30 21:10:40.736  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EISCONN 192.168.123.45:55443 - Local (192.168.178.30:34224)</td></tr><tr class="debug"><td>2022-05-30 21:10:42.611  - <span class="type">debug</span>: yeelight-2.0 (3148) YEELIGHT OFFLINE: 0x0000000005e880b4</td></tr><tr class="debug"><td>2022-05-30 21:10:53.744  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EISCONN 192.168.123.45:55443 - Local (192.168.178.30:34226)</td></tr><tr class="debug"><td>2022-05-30 21:11:23.746  - <span class="type">debug</span>: yeelight-2.0 (3148) ERROR YEELIGHT CONNECTION: 0x0000000005e880b4: Connection 192.168.123.45:55443: Error: connect EISCONN 192.168.123.45:55443 - Local (192.168.178.30:34230)</td></tr><tr class="debug"><td>2022-05-30 21:11:42.613  - <span class="type">debug</span>: yeelight-2.0 (3148) YEELIGHT OFFLINE: 0x0000000005e880b4</td></tr><tr class="debug"><td>2022-05-30 21:12:36.147  - <span class="type">debug</span>: yeelight-2.0 (3148) SEND STATE: id:0x0000000005e880b4, state: moon_mode, value: true</td></tr><tr class="debug"><td>2022-05-30 21:12:36.163  - <span class="type">debug</span>: yeelight-2.0 (3148) RESPONSE MESSAGE: from: 0x0000000005e880b4, id: 2, result:[ok]}</td></tr><tr class="debug"><td>2022-05-30 21:12:36.169  - <span class="type">debug</span>: yeelight-2.0 (3148) NOTIFY MESSAGE: from: 0x0000000005e880b4, message: {"method":"props","params":{"nl_br":100,"active_mode":1,"active_bright":100}}</td></tr><tr class="debug"><td>2022-05-30 21:12:36.171  - <span class="type">debug</span>: yeelight-2.0 (3148) DEVICE FOUND SET NOTIFY STATE: {"name":"ceiling4-0x0000000005e880b4","ip":"192.168.123.45","port":"55443","smart_name":"","type":"ceiling4","id":"0x0000000005e880b4"}</td></tr><tr class="debug"><td>2022-05-30 21:12:54.188  - <span class="type">debug</span>: yeelight-2.0 (3148) SEND STATE: id:0x0000000005e880b4, state: moon_mode, value: false</td></tr><tr class="debug"><td>2022-05-30 21:12:54.204  - <span class="type">debug</span>: yeelight-2.0 (3148) RESPONSE MESSAGE: from: 0x0000000005e880b4, id: 3, result:[ok]}</td></tr><tr class="debug"><td>2022-05-30 21:12:54.209  - <span class="type">debug</span>: yeelight-2.0 (3148) NOTIFY MESSAGE: from: 0x0000000005e880b4, message: {"method":"props","params":{"nl_br":0,"active_mode":0,"active_bright":61}}</td></tr><tr class="debug"><td>2022-05-30 21:12:54.209  - <span class="type">debug</span>: yeelight-2.0 (3148) DEVICE FOUND SET NOTIFY STATE: {"name":"ceiling4-0x0000000005e880b4","ip":"192.168.123.45","port":"55443","smart_name":"","type":"ceiling4","id":"0x0000000005e880b4"}</td></tr><tr class="debug"><td>2022-05-30 21:13:55.634  - <span class="type">debug</span>: yeelight-2.0 (3148) SEND STATE: id:0x0000000005e880b4, state: active_bright, value: 50</td></tr><tr class="debug"><td>2022-05-30 21:13:55.681  - <span class="type">debug</span>: yeelight-2.0 (3148) RESPONSE MESSAGE: from: 0x0000000005e880b4, id: 4, result:[ok]}</td></tr><tr class="debug"><td>2022-05-30 21:13:55.687  - <span class="type">debug</span>: yeelight-2.0 (3148) NOTIFY MESSAGE: from: 0x0000000005e880b4, message: {"method":"props","params":{"bright":50,"active_bright":50}}</td></tr><tr class="debug"><td>2022-05-30 21:13:55.687  - <span class="type">debug</span>: yeelight-2.0 (3148) DEVICE FOUND SET NOTIFY STATE: {"name":"ceiling4-0x0000000005e880b4","ip":"192.168.123.45","port":"55443","smart_name":"","type":"ceiling4","id":"0x0000000005e880b4"}</td></tr></tbody></table>

**Comment by Apollon77** [comment]
Ok, then we need other log :-)

Please stop the adapter, then ogin via SSH to the iobroker host and execute

´DEBUG=Yeelight* iob debug yeelight-2`

and check again when such stuff happens and pst the console output please (opr attach as file)
