### ISSUE TITLE
GU10 Yeelight not working

### ISSUE THREAD

**Issue by MrDfromLA** [MeisterTR/ioBroker.yeelight#177]
Hi, 
I wanted to add yeelight spotlights (GU10) to iobroker. Everything works as usually smooth, but the control folder is empty so that I am not able to control the spots.

**Comment by Apollon77** [comment]
Please hsow a debug log for the instance - change loglevel in admin instances with active expertmode

**Comment by MrDfromLA** [comment]
I hope, this is it what you meant

[GU10Logfile.txt](https://github.com/iobroker-community-adapters/ioBroker.yeelight-2/files/8823234/GU10Logfile.txt)

**Comment by Apollon77** [comment]
And which device is missing? In fact the device states come as soon as  the device is connected and delivers first values. Wenn das YEELIGHT FOUND oim Log st wurde das Gerät gefunden und die Werte abgefragt ... sodie Frageist was kommt "danach" im Log?

**Comment by MrDfromLA** [comment]
[GU10Logfile_2.txt](https://github.com/iobroker-community-adapters/ioBroker.yeelight-2/files/8846899/GU10Logfile_2.txt)

anbei nochmal. Sorry, es sind halt viele Lampen. (IP der betroffenen GU10: 192.168.2.98)

**Comment by Apollon77** [comment]
Also dieses Gerät hat in der Konfig keinen typ gesetzt ... ist das korrekt so? Sollte da nicht der Typ der Lampe gesetzt sein?

**Comment by MrDfromLA** [comment]
Ich habe alle Konfigurationen (Spalte Art) durchprobiert ohne Erfolg.

**Comment by Apollon77** [comment]
Hast du mal ein Debug log mit einer gesetzten Art die passen sollte?

**Comment by MrDfromLA** [comment]
[GU10Logfile_3.txt](https://github.com/iobroker-community-adapters/ioBroker.yeelight-2/files/8975107/GU10Logfile_3.txt)

Habe den Art auf Mono gesetzt. Sollte passen

**Comment by Apollon77** [comment]
Ok, also mein Tip ist das er issues hat zum gerät zu verbinden. kannst Du vom ioBroker Host aus die IP mit "ping" erreichen. Wenn nicht haste deinen grund :-) vllt auch Gerät mal stromlos machen? SIcher ist sicher. Wenn das nicht hilft.

Dann machmer nochmal anders um mehr log zu bekommen :-)

1.) Bitte GitHub version installieren - versionsnummer bleibt gleich (GitHub install kann mit npm 6 sehr lange dauern aktuell. geduld haben!)
2.) Adapter stoppen!
3.) SSH einloggen
4.) Adapter manuell mittels `DEBUG=Yeelight* iob debug yeelight2.0` starten

Dann log posten was an der Konsole ausgegeben wird :-) Dann sollte wenn wir glück haben mehr sein mit der IP bzw der geräte ID

**Comment by MrDfromLA** [comment]
Du bringst mich über den Rand meiner Fähigkeiten... Kann ich dir einfach eine Lampe schenken? :-)

**Comment by Apollon77** [comment]
;-) Komm da ist nicht so schlimm. So machen wie ich es gesagt habe. Ist ganz einfach :-)

Schritt 4 ist einfach;: Das genannte Kommando im SSH-Fenster ausführen

Die Frage ist jalt ob ich das gleiche Issue hätte wenn ich Sie hier hätte ...
