### ISSUE TITLE
terminated with code 6 (UNCAUGHT_EXCEPTION)

### ISSUE THREAD

**Issue by JayP666** [MeisterTR/ioBroker.yeelight#178]
<html>
<body>

host.ioBroker | 2022-04-26 12:32:14.727 | error | instance system.adapter.yeelight-2.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at processImmediate (node:internal/timers:473:21)
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:280:25)
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at createDevice (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:437:45)
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at listener (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:465:17)
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at new YeelightSearch (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/index.js:47:20)
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at new SsdpClient (/opt/iobroker/node_modules/node-ssdp/lib/client.js:40:8)
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at SsdpClient.SSDP (/opt/iobroker/node_modules/node-ssdp/lib/index.js:82:8)
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at SsdpClient.SSDP._init (/opt/iobroker/node_modules/node-ssdp/lib/index.js:127:54)
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at Object.ip.address (/opt/iobroker/node_modules/ip/lib/ip.js:379:37)
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at Array.map (<anonymous>)
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at /opt/iobroker/node_modules/ip/lib/ip.js:384:37
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at Array.filter (<anonymous>)
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: at /opt/iobroker/node_modules/ip/lib/ip.js:385:39
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: TypeError: details.family.toLowerCase is not a function
host.ioBroker | 2022-04-26 12:32:14.727 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

</body>
</html>

**Comment by JayP666** [comment]
???

**Comment by Apollon77** [comment]
Node.js 18? This is currently an issue because oif a breaking change in node.js 18 which will be reverted in a 18.x soon ... dowengrade node.js please for now

**Comment by msecker** [comment]
I got a similar problem, node version is 16:
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/14311931/187269853-05371ded-10a5-4c70-8888-c5cd39e2ae09.png">

I recently updated iobroker and especially js-controller (3.3.22) and finally yeelight adapter (1.1.2) but now the adapter wont start.

**Comment by Apollon77** [comment]
Please try 1.2.1 from beta channel/github

**Comment by 2scorpio** [comment]
i have this problem in version 1.2.1

<html>
<body>


yeelight-2.0 | 2022-08-29 22:37:10.291 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
yeelight-2.0 | 2022-08-29 22:37:10.272 | error | Exception-Code: ERR_INVALID_ARG_TYPE: The "options.port" property must be one of type number or string. Received null
yeelight-2.0 | 2022-08-29 22:37:10.271 | error | TypeError [ERR_INVALID_ARG_TYPE]: The "options.port" property must be one of type number or string. Received null at new NodeError (internal/errors.js:322:7) at lookupAndConnect (net.js:1010:13) at Socket.connect (net.js:989:5) at new Yeelight (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/Yeelight.js:126:18) at YeelightSearch.addInitLights (/opt/iobroker/node_modules/iobroker.yeelight-2/yeelight-wifi/build/index.js:104:22) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:490:74) at listOnTimeout (internal/timers.js:557:17) at processTimers (internal/timers.js:500:7)
yeelight-2.0 | 2022-08-29 22:37:10.271 | error | uncaught exception: The "options.port" property must be one of type number or string. Received null
yeelight-2.0 | 2022-08-29 22:37:10.259 | error | Try to create device with empty name!
yeelight-2.0 | 2022-08-29 22:37:10.257 | error | Try to create device with empty name!


</body>
</html>

**Comment by msecker** [comment]
thanks, 1.2.1 from beta channel indeed fixed the issue 👍

**Comment by Apollon77** [comment]
@2scorpio seems that there is a very strange device in your network ... without a name and also without port in discovery ... will look into is in next days

**Comment by Apollon77** [comment]
@2scorpio Pleaase set loglevel of the instance to debug and post a ebug log till that error
