### ISSUE TITLE
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by FogfiRED** [MeisterTR/ioBroker.yeelight#187]
When I try to set a state for the yeelight device, more often it produces the error:

`warn   Could not set state (moon_mode) to value (false) for device: 0x0000000005e881e4. Error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
yeelight-2.0
warn   Could not set state (moon_mode) to value (true) for device: 0x0000000005e881e4. Error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
info   starting. Version 1.2.0 (non-npm: iobroker-community-adapters/ioBroker.yeelight-2) in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v14.19.1, js-controller: 4.0.21`

Restarting the instance does not help.

**Comment by Apollon77** [comment]
In fact this msotly means that the devcie closed the connection ... pease peovide a debug log (Set logelevel of the instance to debug)
