### ISSUE TITLE
Error in Scan mode

### ISSUE THREAD

**Issue by 2scorpio** [MeisterTR/ioBroker.yeelight#188]
Hello.
I started Find mode and see this error in log.
Fix please.

yeelight-2.0 | 2022-05-13 00:58:26.017 | info | starting. Version 1.2.0 (non-npm: iobroker-community-adapters/ioBroker.yeelight-2#05a5208ac349306ec99e01122a5147100b406f4e) in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v14.19.2, js-controller: 4.0.23
yeelight-2.0 | 2022-05-13 00:57:54.285 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
yeelight-2.0 | 2022-05-13 00:57:54.284 | info | terminating
yeelight-2.0 | 2022-05-13 00:57:54.283 | info | cleaned everything up...
yeelight-2.0 | 2022-05-13 00:57:54.272 | error | Yeelights.removeEventListener is not a function
yeelight-2.0 | 2022-05-13 00:57:54.272 | error | TypeError: Yeelights.removeEventListener is not a function at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:105:40) at listOnTimeout (internal/timers.js:557:17) at processTimers (internal/timers.js:500:7)
yeelight-2.0 | 2022-05-13 00:57:54.271 | error | uncaught exception: Yeelights.removeEventListener is not a function

**Comment by Apollon77** [comment]
Fixed on GitHub

**Comment by 2scorpio** [comment]
In version 1.2.0 "Find" still not work :(

**Comment by Apollon77** [comment]
That means? Please provide a debug log

**Comment by 2scorpio** [comment]
`<html>
<body>


yeelight-2.0 | 2022-05-31 22:00:49.666 | debug | here is a Message{"command":"discovery","message":{"turnon":1},"from":"system.adapter.admin.0","callback":{"message":{"turnon":1},"id":56,"ack":false,"time":1654023649662},"_id":34780034}
-- | -- | -- | --
yeelight-2.0 | 2022-05-31 22:00:45.894 | debug | ERROR YEELIGHT CONNECTION: 0x000000000000000: Connection 192.168.2.218:55443: Error: connect EHOSTUNREACH 192.168.2.218:55443
yeelight-2.0 | 2022-05-31 22:00:42.823 | debug | YEELIGHT FOUND: 192.168.2.218:55443 id: 0x000000000000000 model: color
yeelight-2.0 | 2022-05-31 22:00:42.814 | debug | SMARTNAME: Зал_1
yeelight-2.0 | 2022-05-31 22:00:42.813 | debug | OLD CONF. FROM OBJ: {"name":"Зал_1","ip":"192.168.2.218","port":"55443","smart_name":"Зал_1","type":"color","id":"0x000000000000000","supports":["get_prop","set_default","set_power","toggle","set_bright","start_cf","stop_cf","set_scene","cron_add","cron_get","cron_del","set_ct_abx","set_rgb","set_hsv","set_adjust","adjust_bright","adjust_ct","adjust_color","set_music","set_name"]}
yeelight-2.0 | 2022-05-31 22:00:42.811 | debug | OBJ_ELEMENT: yeelight-2.0.Зал_1
yeelight-2.0 | 2022-05-31 22:00:42.811 | debug | DEVICES IN OBJECTS FOUND: 1
yeelight-2.0 | 2022-05-31 22:00:42.810 | debug | DEVICES IN OBJECTS: {"yeelight-2.0.Зал_1":{"type":"device","common":{"name":"color","icon":"/icons/color.png"},"native":{"sid":"Зал_1","type":"color"},"from":"system.adapter.yeelight-2.0","user":"system.user.admin","ts":1652393158196,"_id":"yeelight-2.0.Зал_1","acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"},"enums":{}}}
yeelight-2.0 | 2022-05-31 22:00:42.761 | debug | DEVICES IN CONFIG: [{"name":"Зал_1","ip":"192.168.2.218","port":"55443","smart_name":"Зал_1","type":"color","id":"0x000000000000000","supports":["get_prop","set_default","set_power","toggle","set_bright","start_cf","stop_cf","set_scene","cron_add","cron_get","cron_del","set_ct_abx","set_rgb","set_hsv","set_adjust","adjust_bright","adjust_ct","adjust_color","set_music","set_name"]}]
yeelight-2.0 | 2022-05-31 22:00:42.722 | info | starting. Version 1.2.0 (non-npm: iobroker-community-adapters/ioBroker.yeelight-2#ace4ab92e98172a05642f567d8b05863bf8a10eb) in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v14.19.2, js-controller: 4.0.23
yeelight-2.0 | 2022-05-31 22:00:42.538 | debug | Plugin sentry Initialize Plugin (enabled=true)
yeelight-2.0 | 2022-05-31 22:00:38.575 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
yeelight-2.0 | 2022-05-31 22:00:38.575 | debug | Plugin sentry destroyed
yeelight-2.0 | 2022-05-31 22:00:38.575 | info | terminating
yeelight-2.0 | 2022-05-31 22:00:38.574 | info | cleaned everything up...
yeelight-2.0 | 2022-05-31 22:00:38.573 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>`

**Comment by 2scorpio** [comment]
Then i Press - Find
`<html>
<body>


yeelight-2.0 | 2022-05-31 22:02:06.484 | debug | here is a Message{"command":"discovery","message":{"turnon":1},"from":"system.adapter.admin.0","callback":{"message":{"turnon":1},"id":57,"ack":false,"time":1654023726481},"_id":34780035}
-- | -- | -- | --



</body>
</html>`

**Comment by 2scorpio** [comment]
And i can`t delete device, who added with his hands.

**Comment by Apollon77** [comment]
Ok, it seems that discobvers a device on IP 192.168.2.218 but when he tries to connect to the relevant port then he gets EHOSTUNREACH which means "the IP is not reachable in the network"- SO please check the network reavhability from iobroker host to the device.

And what you mean by "i can`t delete device, who added with his hands." To delete devices simple stop adapter, delete the relevamt objects in ioBroker and restart adapter

**Comment by 2scorpio** [comment]
IP 192.168.2.218 I put this with my hands for the test.
Now I can't delete it.
Through stopping the adapter and deleting the object, I tried.
Failed: (

**Comment by Apollon77** [comment]
Whats the error when it fails?
