### ISSUE TITLE
Strip 1s wird nicht gefunden

### ISSUE THREAD

**Issue by ZeroQool007** [MeisterTR/ioBroker.yeelight#219]
Hallo, zuerst einmal ein richtig guter Adapter. Habe damit mehrere noch alte yeelight Stripes eingebunden und das funktioniert sehr gut. Nun habe ich mir einen Strip 1S geholt und in die Yeelight App eingebunden. Kein Problem, allerdings findet der Adapter den Strip nicht. Manuell hinzufügen geht auch nicht, weil der Adapter nicht mehr hochfährt mit der Begründung Port muss ein korrekter Datentyp sein, aber der ist definitiv korrekt. Hast du eine Idee? Danke

Gruß

**Comment by mcm1957** [comment]
> Manuell hinzufügen geht auch nicht, weil der Adapter nicht mehr hochfährt mit der Begründung Port muss ein korrekter Datentyp sein, aber der ist definitiv korrekt. Hast du eine Idee? Danke

Bitte einen Log mizt dem Fehler anhängen.
Weiters bitte betroffene Adapterversion sowie node / js-controller Versionen angeben.

**Comment by mcm1957** [comment]
keine infos erhalten
Bitte bei Bedarf ein neues issue öffnen
