### ISSUE TITLE
Nach Node.js 18.15 update error

### ISSUE THREAD

**Issue by denjo82** [MeisterTR/ioBroker.yeelight#227]
Habe nach dem nodejs update auf 18.15 folgende Fehlermeldung 
`  

 
--
host.iobroker | 2023-04-02 21:20:59.490 | info | Restart adapter system.adapter.yeelight-2.0 because enabled
host.iobroker | 2023-04-02 21:20:59.489 | error | instance system.adapter.yeelight-2.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2023-04-02 21:20:59.489 | error | Caught by controller[0]: at TCP.<anonymous> (node:net:322:12)
host.iobroker | 2023-04-02 21:20:59.489 | error | Caught by controller[0]: at Socket.emit (node:domain:489:12)
host.iobroker | 2023-04-02 21:20:59.489 | error | Caught by controller[0]: at Socket.emit (node:events:525:35)
host.iobroker | 2023-04-02 21:20:59.489 | error | Caught by controller[0]: at Object.onceWrapper (node:events:628:26)
host.iobroker | 2023-04-02 21:20:59.489 | error | Caught by controller[0]: at Socket.onClose (node:net:911:10)
host.iobroker | 2023-04-02 21:20:59.489 | error | Caught by controller[0]: at new NodeError (node:internal/errors:399:5)
host.iobroker | 2023-04-02 21:20:59.488 | error | Caught by controller[0]: Error: Socket closed before the connection was established
host.iobroker | 2023-04-02 21:20:59.488 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
yeelight-2.0 | 2023-04-02 21:20:58.754 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
yeelight-2.0 | 2023-04-02 21:20:58.749 | info | terminating
yeelight-2.0 | 2023-04-02 21:20:58.748 | info | cleaned everything up...
yeelight-2.0 | 2023-04-02 21:20:58.697 | error | Exception-Code: ERR_SOCKET_CLOSED_BEFORE_CONNECTION: Socket closed before the connection was established
yeelight-2.0 | 2023-04-02 21:20:58.696 | error | Error: Socket closed before the connection was established at new NodeError (node:internal/errors:399:5) at Socket.onClose (node:net:911:10) at Object.onceWrapper (node:events:628:26) at Socket.emit (node:events:525:35) at Socket.emit (node:domain:489:12) at TCP.<anonymous> (node:net:322:12)
yeelight-2.0 | 2023-04-02 21:20:58.694 | error | unhandled promise rejection: Socket closed before the connection was established
yeelight-2.0 | 2023-04-02 21:20:58.690 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
yeelight-2.0 | 2023-04-02 21:20:57.862 | info | starting. Version 1.2.1 (non-npm: iobroker-community-adapters/ioBroker.yeelight-2#2927cdb26f938e958726504bfa2d6dec43049b77) in /opt/iobroker/node_modules/iobroker.yeelight

  `

**Comment by raldi01** [comment]
Bei mir ein ähnliches Problem, nach dem Update auf Node.js: v18.15.0 und NPM: 9.5.0
folgende Einträge im Log:
`<html><body>


yeelight-2.0 | 2023-04-03 11:09:18.832 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
yeelight-2.0 | 2023-04-03 11:09:18.832 | debug | Plugin sentry destroyed
yeelight-2.0 | 2023-04-03 11:09:18.831 | info | terminating
yeelight-2.0 | 2023-04-03 11:09:18.831 | info | cleaned everything up...
yeelight-2.0 | 2023-04-03 11:09:18.830 | error | Exception-Code: ERR_SOCKET_CLOSED_BEFORE_CONNECTION: Socket closed before the connection was established
yeelight-2.0 | 2023-04-03 11:09:18.830 | error | Error  [ERR_SOCKET_CLOSED_BEFORE_CONNECTION]: Socket closed before the  connection was established    at new NodeError  (node:internal/errors:399:5)    at Socket.onClose (node:net:911:10)     at Object.onceWrapper (node:events:628:26)    at Socket.emit  (node:events:525:35)    at TCP.<anonymous> (node:net:322:12)
yeelight-2.0 | 2023-04-03 11:09:18.830 | error | unhandled promise rejection: Socket closed before the connection was established
yeelight-2.0 | 2023-04-03 11:09:18.830 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
yeelight-2.0 | 2023-04-03 11:09:18.830 | error | Exception-Code: ETIMEDOUT: connect ETIMEDOUT 192.168.69.65:55443
yeelight-2.0 | 2023-04-03 11:09:18.830 | error | Error: connect ETIMEDOUT 192.168.69.65:55443    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
yeelight-2.0 | 2023-04-03 11:09:18.830 | error | unhandled promise rejection: connect ETIMEDOUT 192.168.69.65:55443
yeelight-2.0 | 2023-04-03 11:09:18.829 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
yeelight-2.0 | 2023-04-03 11:09:18.829 | error | Exception-Code: ETIMEDOUT: connect ETIMEDOUT 192.168.69.65:55443
yeelight-2.0 | 2023-04-03 11:09:18.829 | error | Error: connect ETIMEDOUT 192.168.69.65:55443    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
yeelight-2.0 | 2023-04-03 11:09:18.829 | error | unhandled promise rejection: connect ETIMEDOUT 192.168.69.65:55443
yeelight-2.0 | 2023-04-03 11:09:18.829 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
yeelight-2.0 | 2023-04-03 11:09:18.829 | error | Exception-Code: ETIMEDOUT: connect ETIMEDOUT 192.168.69.65:55443
yeelight-2.0 | 2023-04-03 11:09:18.829 | error | Error: connect ETIMEDOUT 192.168.69.65:55443    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
yeelight-2.0 | 2023-04-03 11:09:18.828 | error | unhandled promise rejection: connect ETIMEDOUT 192.168.69.65:55443
yeelight-2.0 | 2023-04-03 11:09:18.828 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
yeelight-2.0 | 2023-04-03 11:09:18.828 | error | Exception-Code: ETIMEDOUT: connect ETIMEDOUT 192.168.69.65:55443
yeelight-2.0 | 2023-04-03 11:09:18.828 | error | Error: connect ETIMEDOUT 192.168.69.65:55443    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
yeelight-2.0 | 2023-04-03 11:09:18.828 | error | unhandled promise rejection: connect ETIMEDOUT 192.168.69.65:55443
yeelight-2.0 | 2023-04-03 11:09:18.827 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().


</body>
</html>`

Adapter in der Version 1.2.1
Die angemeckerte Leuchte ist im Unifi-Controller die ganze Zeit online.

**Comment by nifu777** [comment]
Habe seit dem gerade durchgeführten Update (v18.15.0) ebenfalls die genannten Probleme:

host.ioBroker-RasPi
2023-04-06 09:13:24.547	info	Restart adapter system.adapter.yeelight-2.0 because enabled
host.ioBroker-RasPi
2023-04-06 09:13:24.547	error	instance system.adapter.yeelight-2.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioBroker-RasPi
2023-04-06 09:13:24.546	error	Caught by controller[1]: at TCP.<anonymous> (node:net:322:12)
host.ioBroker-RasPi
2023-04-06 09:13:24.546	error	Caught by controller[1]: at Socket.emit (node:domain:489:12)
host.ioBroker-RasPi
2023-04-06 09:13:24.545	error	Caught by controller[1]: at Socket.emit (node:events:525:35)
host.ioBroker-RasPi
2023-04-06 09:13:24.545	error	Caught by controller[1]: at Object.onceWrapper (node:events:628:26)
host.ioBroker-RasPi
2023-04-06 09:13:24.545	error	Caught by controller[1]: at Socket.onClose (node:net:911:10)
host.ioBroker-RasPi
2023-04-06 09:13:24.544	error	Caught by controller[1]: at new NodeError (node:internal/errors:399:5)
host.ioBroker-RasPi
2023-04-06 09:13:24.544	error	Caught by controller[1]: Error: Socket closed before the connection was established
host.ioBroker-RasPi
2023-04-06 09:13:24.543	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

yeelight-2.0
28279	2023-04-06 09:13:23.846	error	Exception-Code: ERR_SOCKET_CLOSED_BEFORE_CONNECTION: Socket closed before the connection was established

yeelight-2.0
28279	2023-04-06 09:13:23.845	error	Error: Socket closed before the connection was established at new NodeError (node:internal/errors:399:5) at Socket.onClose (node:net:911:10) at Object.onceWrapper (node:events:628:26) at Socket.emit (node:events:525:35) at Socket.emit (node:domain:489:12) at TCP.<anonymous> (node:net:322:12)

yeelight-2.0
28279	2023-04-06 09:13:23.844	error	unhandled promise rejection: Socket closed before the connection was established

yeelight-2.0
28279	2023-04-06 09:13:23.842	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
host.ioBroker-RasPi
2023-04-06 09:13:18.507	info	instance system.adapter.yeelight-2.0 started with pid 28279
host.ioBroker-RasPi
2023-04-06 09:13:17.970	info	"system.adapter.yeelight-2.0" enabled

**Comment by locito09** [comment]
Habe auch das Problem nach Update auf Node 18

**Comment by hilde0407** [comment]
Ich habe das selbe Problem und hoffe, dass der Fehler bald behoben werden kann, da ich in meinem Smarthome eine ganze Menge Yeelight Lampen habe.

**Comment by nifu777** [comment]
> Ich habe das selbe Problem und hoffe, dass der Fehler bald behoben werden kann, da ich in meinem Smarthome eine ganze Menge Yeelight Lampen habe.

Ich habe/hatte das selbe Problem. Habe versucht den Adapter neu zu installieren, aber Fehler blieb bestehen. Bin nun mit Hilfe [dieser Anleitung (NodeJS Installation)](https://forum.iobroker.net/topic/64032/update-nodejs-best-practise-supported-14-16-und-18) vorerst wieder auf v16 (v16.19.1) und der Yeelight Adapter ist nun wieder nutzbar und erzeugt keine Fehler

**Comment by denjo1982** [comment]
wird eigentlich an einer lösung gearbeitet??

**Comment by mcm1957** [comment]
Derzeit wird nach meiner Kenntnis nicht aktiv an einer Lösung gearbeitet.

Bitte aber die immer benötigten und hier noch nicht gelisteten Infos ergänzen:

Adapterversion
js-controller Version

Insbesonder bitte sicherstellen, dass die **aktuellste Version des js-controllers (4.0.24)** verwendet wird. Bei dieser wurden Anpassungen für node 18 umgesetzt.

**Comment by TDCroPower** [comment]
Bei mir auch mit folgenden Versionen...

Adapterversion: 1.2.1
js-controller: 4.0.24

**Comment by Flauschi83** [comment]
ich hänge mich mal mit an.
Same problem.

gibts dafür eine  workaround?

**Comment by SvenJ76** [comment]
Gleiches Problem hier mit den gleichen Versionen von Controller und Adapter

**Comment by mcm1957** [comment]
Könnte jemand von euch mal die GITHUB Version testen?
Wenn ich es richtig in den Releasenotes sehe hat @Apollon77 vior einiger Zeit etwas am reconnect gefixed dass noch in keiner Release enthalten ist:

(Apollon77) make sure reconnects work correctly

Sollte das was helfen, kan ich eine neue Release erstellen. Mangels passender Hardware kann ich aber leider nichts testen / analysieren.

**Comment by locito09** [comment]
Vom Github installiert,leider keine änderung

**Comment by locito09** [comment]
gib es schon was neues? würde gerne meine Lampen wieder bedienen können

**Comment by mcm1957** [comment]
Nein
Mein letztes Posting sollte nur darauf hinweisen, dass etwas Neueres auf Github existiert.
Soweit mir bekannt gibtr es zur Zeit keinen Entwickler der aktiv an diesem Adapter dran ist. Sorry.

**Comment by Snatch2001** [comment]
Bei mir auch das gleiche Problem. Gibt es Alternativen zu diesem Adapter?

**Comment by SvenJ76** [comment]
Lösung hatte bei mir gebracht, nachzuschauen ob wirklich alle im Adapter eingetragenen Lampen auch erreichbar sind. Ich hatte eine Altlast drin die so nicht mehr gab und deshalb ist er auf die Nase gefallen. Lampe gelöscht, schon ging's wieder.

**Comment by denjo1982** [comment]
also läuft der adapter bei dir wieder??? welche version?

**Comment by denjo1982** [comment]
tatsache adapter läuft wieder

**Comment by denjo1982** [comment]
also zur info, ich habe die erfahrungen gemacht das die lampe/lampen eingeschaltet sein müssen beim adapter start und ich hatte zusätzlich die app auch offen

**Comment by Ilovegym66** [comment]
Der Fehler tritt nur auf, wenn ein Device offline ist, solange alle online sind, laeuft der Adapter ohne Fehler.
Hier sollte also der Fehler besser abgefangen werden vom Adapter. Da hier alle Leuchten immer online sind, tritt der Fehler nicht auf, kann es aber nachvollziehen, wenn ich bei einer den Stecker zieh..

**Comment by W0RSCHD** [comment]
> Der Fehler tritt nur auf, wenn ein Device offline ist, solange alle online sind, laeuft der Adapter ohne Fehler. Hier sollte also der Fehler besser abgefangen werden vom Adapter. Da hier alle Leuchten immer online sind, tritt der Fehler nicht auf, kann es aber nachvollziehen, wenn ich bei einer den Stecker zieh..

kann ich bestätigen, sind alle Teilnehmer erreichbar, startet der Adapter und läuft... Ein Fix dass der Adapter bei nicht erreichbaren Geräten crashed wäre schön :)

**Comment by Apollon77** [comment]
Kann jemand mal debug logs posten von "alle da" und "einer nicht" oder so? Dann kann man vllt mal die unterschiede ansehen

**Comment by TDCroPower** [comment]
Bei mir ist es die Meteorit Lampe die seit einiger Zeit nicht connected mit dem Adapter.
Müsste ich an anderer Stelle mal checken, weil die eigentlich im Netzwerk vertreten ist.

@Apollon77 kann ich machen, da ich iobroker im Docker laufen lasse kann ich schnell wechseln.
Was willst du denn genau für Logs haben oder lediglich die Yeelight2 Instanz im Debug und davon den Auszug?

**edit:**
hier erstmal das debug log von einem fehlerhaften Start.
Offline Meteorit + Config in der Instanz...
https://pastebin.com/NEJHhuiL

Ohne Meteorit Config...
https://pastebin.com/GGgXeWrn

Und hier nachdem ich alle gemeldeten offline devices entfernt habe, sodass der Adapter aktiv bleibt...
https://pastebin.com/jrcFkvzW

sauberer Start ohne Offline Device Reste in Config + Objekten...
https://pastebin.com/YLNiTspT

**edit2:**
habe eben auch mal den "Find" getestet, er findet die von mir entfernten Geräte nicht.
Entferne ich einen der "guten" Geräte wird dieser mit dem "Find" Button direkt gefunden...
![Bildschirmfoto 2023-08-23 um 15 48 18](https://github.com/iobroker-community-adapters/ioBroker.yeelight-2/assets/6634116/8c50cf08-0842-4d27-a41a-57784428bfea)

**edit3:**
ok, der Grund meiner offline Geräte habe ich gefunden, die "LAN Steuerung" war deaktiviert.
Jetzt werden sie über den "Find" Button gefunden ;)
Dadurch kann man den Adapter aber jederzeit testen um den offline Zustand zu "simulieren".

**Comment by ArchGithub** [comment]
Hallo, ich habe auch das Problem.
Wenn 12 Lampen gleichzeitig online sein müssen bei jeden reboot nervt das.
@Apollon77

`
yeelight-2.1 | 2023-08-30 21:46:07.984 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
yeelight-2.1 | 2023-08-30 21:46:07.956 | error | Exception-Code: ERR_SOCKET_CLOSED_BEFORE_CONNECTION: Socket closed before the connection was established
yeelight-2.1 | 2023-08-30 21:46:07.955 | error | Error: Socket closed before the connection was established at new NodeError (node:internal/errors:405:5) at Socket.onClose (node:net:912:10) at Object.onceWrapper (node:events:629:26) at Socket.emit (node:events:526:35) at Socket.emit (node:domain:489:12) at TCP.<anonymous> (node:net:323:12)
yeelight-2.1 | 2023-08-30 21:46:07.954 | error | unhandled promise rejection: Socket closed before the connection was established
yeelight-2.1 | 2023-08-30 21:46:07.953 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
`

Grüße

**Comment by MegaMatze** [comment]
Mist, nach NodeJS update auf 20 geht der Adapter bei mir auch nicht mehr. Hat wer einen Workaround, bis da ein Update da ist? Bei mir ist gerade einiges im Haus dunkel, das ist ein bisschen ärgerlich....

**Comment by mcm1957** [comment]
@MegaMatze 
Welche  Node Version?
Welche Adapter Version?
Welche js-controller version?

**Comment by MegaMatze** [comment]
> @MegaMatze Welche Node Version? Welche Adapter Version? Welche js-controller version?

Node.js:
v20.7.0
jsController:
4.0.24
yeelight:
1.2.1

**Comment by maxpd1** [comment]
Same problem

`<html>
<body>


yeelight-2.0 | 2023-10-11 11:28:13.373 | error | Exception-Code: ERR_SOCKET_CLOSED_BEFORE_CONNECTION: Socket closed before the connection was established
-- | -- | -- | --
yeelight-2.0 | 2023-10-11 11:28:13.373 | error | Error: Socket closed before the connection was established at new NodeError (node:internal/errors:405:5) at Socket.onClose (node:net:912:10) at Object.onceWrapper (node:events:629:26) at Socket.emit (node:events:526:35) at Socket.emit (node:domain:489:12) at TCP.<anonymous> (node:net:323:12)
yeelight-2.0 | 2023-10-11 11:28:13.372 | error | unhandled promise rejection: Socket closed before the connection was established
yeelight-2.0 | 2023-10-11 11:28:13.371 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
yeelight-2.0 | 2023-10-11 11:28:13.156 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
yeelight-2.0 | 2023-10-11 11:28:13.154 | info | terminating
yeelight-2.0 | 2023-10-11 11:28:13.153 | info | cleaned everything up...
yeelight-2.0 | 2023-10-11 11:28:13.105 | error | Exception-Code: ERR_SOCKET_CLOSED_BEFORE_CONNECTION: Socket closed before the connection was established
yeelight-2.0 | 2023-10-11 11:28:13.103 | error | Error: Socket closed before the connection was established at new NodeError (node:internal/errors:405:5) at Socket.onClose (node:net:912:10) at Object.onceWrapper (node:events:629:26) at Socket.emit (node:events:526:35) at Socket.emit (node:domain:489:12) at TCP.<anonymous> (node:net:323:12)
yeelight-2.0 | 2023-10-11 11:28:13.102 | error | unhandled promise rejection: Socket closed before the connection was established
yeelight-2.0 | 2023-10-11 11:28:13.101 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
yeelight-2.0 | 2023-10-11 11:28:09.709 | info | starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v18.17.1, js-controller: 5.0.12


</body>
</html>`


Nodejs: 18.17.1
jscontroller: 5.0.12

**Comment by mcm1957** [comment]
fixed with 1.3.1
